//! Output file format enumeration.
//!
//! Ported from: net/sourceforge/plantuml/FileFormat.java

use std::collections::HashMap;
use std::sync::LazyLock;

/// Format for output files generated by `PlantUML`.
///
/// The AWT-dependent `getDefaultStringBounder` is intentionally omitted here;
/// string-bounder selection lives in the `plantuml-klimt` / backend crates.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FileFormat {
    Eps,
    EpsText,
    Atxt,
    Utxt,
    XmiStandard,
    XmiStar,
    XmiArgo,
    XmiCustom,
    XmiScript,
    Scxml,
    Graphml,
    Pdf,
    Html,
    Html5,
    Vdx,
    Latex,
    LatexNoPreamble,
    LatexDeterministic,
    Base64,
    BraillePng,
    Obfuscate,
    Debug,
    Null,
    Preproc,
    Png,
    PngEmpty,
    Raw,
    SvgDeterministic,
    Svg,
}

impl FileFormat {
    /// The CLI name (e.g. `"svg"`, `"png"`, `"preproc"`).
    #[must_use]
    pub const fn name(&self) -> &'static str {
        match self {
            Self::EpsText => "eps-text",
            Self::Atxt => "txt",
            Self::Utxt => "utxt",
            Self::XmiStandard => "xmi",
            Self::XmiStar => "xmi-star",
            Self::XmiArgo => "xmi-argo",
            Self::XmiCustom => "xmi-custom",
            Self::XmiScript => "xmi-script",
            Self::Scxml => "scxml",
            Self::Graphml => "graphml",
            Self::Pdf => "pdf",
            Self::Html => "html",
            Self::Html5 => "html5",
            Self::Vdx => "vdx",
            Self::LatexNoPreamble => "eps-no-preamble",
            Self::Eps | Self::Latex | Self::LatexDeterministic => "eps",
            Self::Base64 => "base64",
            Self::BraillePng => "braille-png",
            Self::Obfuscate => "obfuscate",
            Self::Debug => "debug",
            Self::Null => "null",
            Self::Preproc => "preproc",
            Self::Png => "png",
            Self::PngEmpty => "png-empty",
            Self::Raw => "raw",
            Self::SvgDeterministic | Self::Svg => "svg",
        }
    }

    /// The MIME type used when serving the format.
    #[must_use]
    pub const fn mime_type(&self) -> &'static str {
        match self {
            Self::Eps | Self::EpsText => "application/postscript",
            Self::Atxt | Self::Obfuscate | Self::Debug | Self::Null | Self::Preproc => "text/plain",
            Self::Utxt => "text/plain;charset=UTF-8",
            Self::XmiStandard
            | Self::XmiStar
            | Self::XmiArgo
            | Self::XmiCustom
            | Self::XmiScript => "application/vnd.xmi+xml",
            Self::Scxml => "application/scxml+xml",
            Self::Graphml => "application/graphml+xml",
            Self::Pdf => "application/pdf",
            Self::Html | Self::Html5 => "text/html",
            Self::Vdx => "application/vnd.visio.xml",
            Self::Latex | Self::LatexNoPreamble | Self::LatexDeterministic => "application/x-latex",
            Self::Base64 => "text/plain; charset=x-user-defined",
            Self::BraillePng | Self::Png | Self::PngEmpty => "image/png",
            Self::Raw => "image/raw",
            Self::SvgDeterministic | Self::Svg => "image/svg+xml",
        }
    }

    /// Returns the file suffix (a string starting with a point).
    #[must_use]
    pub const fn file_suffix(&self) -> &'static str {
        match self {
            Self::XmiCustom => ".xmi_custom",
            Self::XmiStandard | Self::XmiStar | Self::XmiArgo | Self::XmiScript => ".xmi",
            Self::Latex | Self::LatexNoPreamble | Self::LatexDeterministic => ".tex",
            Self::BraillePng => ".braille.png",
            Self::SvgDeterministic | Self::Svg => ".svg",
            Self::EpsText | Self::Eps => ".eps",
            Self::Atxt => ".txt",
            Self::Utxt => ".utxt",
            Self::Scxml => ".scxml",
            Self::Graphml => ".graphml",
            Self::Pdf => ".pdf",
            Self::Html => ".html",
            Self::Html5 => ".html5",
            Self::Vdx => ".vdx",
            Self::Base64 => ".base64",
            Self::Obfuscate => ".obfuscate",
            Self::Debug => ".debug",
            Self::Null => ".null",
            Self::Preproc => ".preproc",
            Self::Png => ".png",
            Self::PngEmpty => ".png-empty",
            Self::Raw => ".raw",
        }
    }

    /// `true` for Encapsulated PostScript formats.
    #[must_use]
    pub const fn is_eps(&self) -> bool {
        matches!(self, Self::Eps | Self::EpsText)
    }

    /// `true` for any XMI variant.
    #[must_use]
    pub const fn is_xmi(&self) -> bool {
        matches!(
            self,
            Self::XmiStandard | Self::XmiStar | Self::XmiArgo | Self::XmiCustom | Self::XmiScript
        )
    }

    /// `true` for formats that support embedded source metadata.
    #[must_use]
    pub const fn does_support_metadata(&self) -> bool {
        matches!(self, Self::Png | Self::Svg)
    }

    /// Look up a format by its CLI name.
    #[must_use]
    pub fn from_cli(name: &str) -> Option<Self> {
        static MAP: LazyLock<HashMap<&'static str, FileFormat>> = LazyLock::new(|| {
            let mut m = HashMap::new();
            for f in FileFormat::all() {
                m.insert(f.name(), f);
            }
            m
        });
        MAP.get(name).copied()
    }

    /// All variants in declaration order.
    #[must_use]
    pub const fn all() -> [Self; 29] {
        [
            Self::Eps,
            Self::EpsText,
            Self::Atxt,
            Self::Utxt,
            Self::XmiStandard,
            Self::XmiStar,
            Self::XmiArgo,
            Self::XmiCustom,
            Self::XmiScript,
            Self::Scxml,
            Self::Graphml,
            Self::Pdf,
            Self::Html,
            Self::Html5,
            Self::Vdx,
            Self::Latex,
            Self::LatexNoPreamble,
            Self::LatexDeterministic,
            Self::Base64,
            Self::BraillePng,
            Self::Obfuscate,
            Self::Debug,
            Self::Null,
            Self::Preproc,
            Self::Png,
            Self::PngEmpty,
            Self::Raw,
            Self::SvgDeterministic,
            Self::Svg,
        ]
    }
}

impl std::fmt::Display for FileFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.name())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_cli_roundtrip() {
        assert_eq!(FileFormat::from_cli("svg"), Some(FileFormat::Svg));
        assert_eq!(FileFormat::from_cli("preproc"), Some(FileFormat::Preproc));
        assert_eq!(FileFormat::from_cli("braille-png"), Some(FileFormat::BraillePng));
        assert_eq!(FileFormat::from_cli("nope"), None);
    }

    #[test]
    fn suffixes() {
        assert_eq!(FileFormat::XmiCustom.file_suffix(), ".xmi_custom");
        assert_eq!(FileFormat::XmiStandard.file_suffix(), ".xmi");
        assert_eq!(FileFormat::Latex.file_suffix(), ".tex");
        assert_eq!(FileFormat::BraillePng.file_suffix(), ".braille.png");
        assert_eq!(FileFormat::SvgDeterministic.file_suffix(), ".svg");
        assert_eq!(FileFormat::EpsText.file_suffix(), ".eps");
    }

    #[test]
    fn predicates() {
        assert!(FileFormat::Eps.is_eps());
        assert!(FileFormat::EpsText.is_eps());
        assert!(!FileFormat::Pdf.is_eps());
        assert!(FileFormat::XmiStar.is_xmi());
        assert!(!FileFormat::Scxml.is_xmi());
        assert!(FileFormat::Png.does_support_metadata());
        assert!(FileFormat::Svg.does_support_metadata());
        assert!(!FileFormat::SvgDeterministic.does_support_metadata());
    }

    #[test]
    fn mime_types() {
        assert_eq!(FileFormat::Svg.mime_type(), "image/svg+xml");
        assert_eq!(FileFormat::Utxt.mime_type(), "text/plain;charset=UTF-8");
    }
}
