//! SName — style selector names.
//!
//! Ported from: `net/sourceforge/plantuml/style/SName.java`

/// Style selector names — the named selectors used in PlantUML styles.
///
/// Ported from: `net/sourceforge/plantuml/style/SName.java`
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum SName {
    Root,
    Document,
    Element,
    ActivityDiagram,
    Activity,
    ActivityArrow,
    ActivityBar,
    ActivityBranch,
    ActivityCircle,
    ActivityDiamond,
    ActivityEnd,
    ActivityFork,
    ActivityIntrusion,
    ActivityJoin,
    ActivityLabel,
    ActivityPartition,
    ActivityStart,
    ActivityTransitionLabel,
    Archimate,
    ArchimateBusiness,
    ArchimateApplication,
    ArchimateMotivation,
    ArchimateImplementation,
    Arrow,
    Artifact,
    Association,
    Background,
    Bar,
    Biddable,
    Body,
    Border,
    Box,
    Caption,
    Card,
    Circle,
    CircleEnd,
    CircleStart,
    Class,
    ClassDiagram,
    CircleInterface,
    Cluster,
    CodeBlock,
    Color,
    Comment,
    Component,
    ComponentDiagram,
    Composite,
    Condition,
    Constraint,
    Control,
    Database,
    Description,
    Dest,
    Diagram,
    Divider,
    Domain,
    Dotted,
    Edge,
    Entity,
    Entry,
    Enum,
    Error,
    Event,
    Exit,
    Explanation,
    Field,
    File,
    Fill,
    Folder,
    Font,
    Fork,
    Group,
    Grouping,
    Hexagon,
    Hide,
    History,
    Icon,
    Interface,
    Json,
    Label,
    Leaf,
    Legend,
    Line,
    Link,
    Lollipop,
    Map,
    Member,
    Mindmap,
    MindmapDiagram,
    MindmapNode,
    Network,
    Node,
    Note,
    Nwdiag,
    NwdiagDiagram,
    Object,
    ObjectDiagram,
    Octagon,
    Package,
    Participant,
    Partition,
    Path,
    Person,
    Port,
    Process,
    Queue,
    Rectangle,
    Reference,
    Requirement,
    RootDiagram,
    Round,
    SelfArrow,
    Sequence,
    SequenceArrow,
    SequenceDiagram,
    SequenceGrouping,
    SequenceLifeLine,
    SequenceParticipant,
    SequenceReference,
    Shape,
    Signal,
    Slot,
    Source,
    State,
    StateDiagram,
    StateTransition,
    Stereotype,
    Storage,
    Stroke,
    Style,
    Subject,
    SyncBar,
    Table,
    Tag,
    Target,
    Text,
    Title,
    Tree,
    Usecase,
    UsecaseDiagram,
    Vertex,
    Wbs,
    WbsDiagram,
    Wire,
    Word,
    Zone,
}

impl SName {
    /// Returns the string name of this selector.
    #[must_use]
    pub fn name(&self) -> &'static str {
        match self {
            Self::Root => "root",
            Self::Document => "document",
            Self::Element => "element",
            Self::ActivityDiagram => "activityDiagram",
            Self::Activity => "activity",
            Self::ActivityArrow => "activityArrow",
            Self::ActivityBar => "activityBar",
            Self::ActivityBranch => "activityBranch",
            Self::ActivityCircle => "activityCircle",
            Self::ActivityDiamond => "activityDiamond",
            Self::ActivityEnd => "activityEnd",
            Self::ActivityFork => "activityFork",
            Self::ActivityIntrusion => "activityIntrusion",
            Self::ActivityJoin => "activityJoin",
            Self::ActivityLabel => "activityLabel",
            Self::ActivityPartition => "activityPartition",
            Self::ActivityStart => "activityStart",
            Self::ActivityTransitionLabel => "activityTransitionLabel",
            Self::Archimate => "archimate",
            Self::ArchimateBusiness => "archimateBusiness",
            Self::ArchimateApplication => "archimateApplication",
            Self::ArchimateMotivation => "archimateMotivation",
            Self::ArchimateImplementation => "archimateImplementation",
            Self::Arrow => "arrow",
            Self::Artifact => "artifact",
            Self::Association => "association",
            Self::Background => "background",
            Self::Bar => "bar",
            Self::Biddable => "biddable",
            Self::Body => "body",
            Self::Border => "border",
            Self::Box => "box",
            Self::Caption => "caption",
            Self::Card => "card",
            Self::Circle => "circle",
            Self::CircleEnd => "circleEnd",
            Self::CircleStart => "circleStart",
            Self::Class => "class",
            Self::ClassDiagram => "classDiagram",
            Self::CircleInterface => "circleInterface",
            Self::Cluster => "cluster",
            Self::CodeBlock => "codeBlock",
            Self::Color => "color",
            Self::Comment => "comment",
            Self::Component => "component",
            Self::ComponentDiagram => "componentDiagram",
            Self::Composite => "composite",
            Self::Condition => "condition",
            Self::Constraint => "constraint",
            Self::Control => "control",
            Self::Database => "database",
            Self::Description => "description",
            Self::Dest => "dest",
            Self::Diagram => "diagram",
            Self::Divider => "divider",
            Self::Domain => "domain",
            Self::Dotted => "dotted",
            Self::Edge => "edge",
            Self::Entity => "entity",
            Self::Entry => "entry",
            Self::Enum => "enum",
            Self::Error => "error",
            Self::Event => "event",
            Self::Exit => "exit",
            Self::Explanation => "explanation",
            Self::Field => "field",
            Self::File => "file",
            Self::Fill => "fill",
            Self::Folder => "folder",
            Self::Font => "font",
            Self::Fork => "fork",
            Self::Group => "group",
            Self::Grouping => "grouping",
            Self::Hexagon => "hexagon",
            Self::Hide => "hide",
            Self::History => "history",
            Self::Icon => "icon",
            Self::Interface => "interface",
            Self::Json => "json",
            Self::Label => "label",
            Self::Leaf => "leaf",
            Self::Legend => "legend",
            Self::Line => "line",
            Self::Link => "link",
            Self::Lollipop => "lollipop",
            Self::Map => "map",
            Self::Member => "member",
            Self::Mindmap => "mindmap",
            Self::MindmapDiagram => "mindmapDiagram",
            Self::MindmapNode => "mindmapNode",
            Self::Network => "network",
            Self::Node => "node",
            Self::Note => "note",
            Self::Nwdiag => "nwdiag",
            Self::NwdiagDiagram => "nwdiagDiagram",
            Self::Object => "object",
            Self::ObjectDiagram => "objectDiagram",
            Self::Octagon => "octagon",
            Self::Package => "package",
            Self::Participant => "participant",
            Self::Partition => "partition",
            Self::Path => "path",
            Self::Person => "person",
            Self::Port => "port",
            Self::Process => "process",
            Self::Queue => "queue",
            Self::Rectangle => "rectangle",
            Self::Reference => "reference",
            Self::Requirement => "requirement",
            Self::RootDiagram => "rootDiagram",
            Self::Round => "round",
            Self::SelfArrow => "selfArrow",
            Self::Sequence => "sequence",
            Self::SequenceArrow => "sequenceArrow",
            Self::SequenceDiagram => "sequenceDiagram",
            Self::SequenceGrouping => "sequenceGrouping",
            Self::SequenceLifeLine => "sequenceLifeLine",
            Self::SequenceParticipant => "sequenceParticipant",
            Self::SequenceReference => "sequenceReference",
            Self::Shape => "shape",
            Self::Signal => "signal",
            Self::Slot => "slot",
            Self::Source => "source",
            Self::State => "state",
            Self::StateDiagram => "stateDiagram",
            Self::StateTransition => "stateTransition",
            Self::Stereotype => "stereotype",
            Self::Storage => "storage",
            Self::Stroke => "stroke",
            Self::Style => "style",
            Self::Subject => "subject",
            Self::SyncBar => "syncBar",
            Self::Table => "table",
            Self::Tag => "tag",
            Self::Target => "target",
            Self::Text => "text",
            Self::Title => "title",
            Self::Tree => "tree",
            Self::Usecase => "usecase",
            Self::UsecaseDiagram => "usecaseDiagram",
            Self::Vertex => "vertex",
            Self::Wbs => "wbs",
            Self::WbsDiagram => "wbsDiagram",
            Self::Wire => "wire",
            Self::Word => "word",
            Self::Zone => "zone",
        }
    }
}
